### ISSUE TITLE
Connection between ad:Address and au:AdministrativeUnit?

### ISSUE THREAD

**Issue by namedgraph** [inspire-eu-rdf/inspire-rdf-vocabularies#2]
I haven't been able to find it.

**Comment by jechterhoff** [comment]
In the conceptual model, there's a route from Address to AdminstrativeUnit via Address.component, which links to the abstract class AddressComponent, which has the subtype AdminUnitName, which links to AdministrativeUnit via  adminUnitName.adminUnit. Not sure if that's what you're looking for.

**Comment by namedgraph** [comment]
Thanks, this might do it.

How about on a purely spatial level? Address has a point/geometry and AdministrativeUnit has geometry. Does any of the vocabularies provide a property for spatial containment? E.g. `dk:Copenhagen containedIn dk:Capital_Region .`

**Comment by jechterhoff** [comment]
Since both Address and AdministrativeUnit are subclasses of GeoSPARQL Feature (and thus GeoSPARQL SpatialThing), the properties for defining spatial relationships as specified by GeoSPARQL chapter 7 (Topology Vocabulary Extension) - e.g. sfWithin - can be used by Address and AdministrativeUnit. 

These properties will likely not be available in original data, though. They could be computed/asserted using a SPARQL query with GeoSPARQL extension functions (see GeoSPARQL chapter 9, Geometry Topology Extension).

**Comment by namedgraph** [comment]
Makes sense. But isn't `sfWithin` identifying a GeoSPARQL *function* rather than a general geospatial relation? These are not exactly the same things.

**Comment by jechterhoff** [comment]
GeoSPARQL defines the relationships both as properties (of SpatialThing) and as functions (to be used in SPARQL queries).

**Comment by namedgraph** [comment]
Found a relevant example in the W3C Spatial Data on the Web Best Practices: https://www.w3.org/TR/2017/NOTE-sdw-bp-20170928/#link-type-spatial-rels
It also mentions `schema:containsPlace`/`schema:containedInPlace` which could make more sense in my case.
